export const TOGGLE_UI_CARD = 'TOGGLE_UI_CARD';

export const ADD_ITEM = 'ADD_ITEM';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const REPLACE_CART = 'REPLACE_CART';

export const INIT_GET_FETCH = 'INIT_GET_FETCH';
export const INIT_PUT_FETCH = 'INIT_PUT_FETCH';

export const PENDING_NOTIFICATION = 'PENDING_NOTIFICATION';
export const SUCCCESS_NOTIFICATION = 'SUCCCESS_NOTIFICATION';
export const ERROR_NOTIFICATION = 'ERROR_NOTIFICATION';

export const OPEN_LOGIN_FORM = 'OPEN_LOGIN_FORM';
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_AUTO_SIGNIN = 'LOGIN_AUTO_SIGNIN';
export const INITIATE_LOGOUT = 'INITIATE_LOGOUT';
export const LOGOUT = 'LOGOUT';
